In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('JenniferPriceData.csv')
data=data.iloc[:,1:]

In [3]:
data.head(5)

Name        Date  Price  DailyChange  WeekChange    MarketCap  \
0  Ethereum  2017-01-04  11.25        15.40       47.31  985511573.0   
1  Ethereum  2017-01-05  10.25        -9.17       22.95  898495324.0   
2  Ethereum  2017-01-06  10.25        -1.08       26.05  898841639.0   
3  Ethereum  2017-01-07   9.87        -3.92       21.76  865194304.0   
4  Ethereum  2017-01-08  10.29         4.41       26.16  902575822.0   

   DailyVolume  lag1_DailyChange  lag2_DailyChange  lag3_DailyChange  \
0   41051196.0             16.33              3.03              1.78   
1   41557420.0             15.40             16.33              3.03   
2   29471794.0             -9.17             15.40             16.33   
3   23153574.0             -1.08             -9.17             15.40   
4   16676626.0             -3.92             -1.08             -9.17   

   lag1_WeekChange  lag1_DailyRank  lag2_DailyRank  lag3_DailyRank  \
0            35.83        0.060606        0.454545        0.393939   
1            47.31        0.303030        0.060606        0.454545   
2            22.95        0.545455        0.303030        0.060606   
3            26.05        0.303030        0.545455        0.303030   
4            21.76        0.878788        0.303030        0.545455   

   lag1_WeekRank  lagN_Price  response  
0       0.121212       10.25     -8.89  
1       0.181818       10.25      0.00  
2       0.212121        9.87     -3.71  
3       0.121212       10.29      4.26  
4       0.181818       10.33      0.39

## Start from data preprocessing

In [4]:
# three matrix: return , price and sort, also the market capitalization matrix

In [5]:
name,length=np.unique(data['Name'].values,return_counts=True)
max_length = max(length)

In [6]:
%%time
price =[]
return_arr = []
mar_cap = []
for i in range(len(name)):
    df=data[data['Name']==name[i]]
    p=df['Price'].values
    r=(df['Price'].diff()/df['Price']).values
    cap=df['MarketCap'].values
    emp = np.empty((max_length-length[i],))
    emp[:] = np.NaN
    price.append(np.concatenate((emp,p)))
    return_arr.append(np.concatenate((emp,r)))
    mar_cap.append(np.concatenate((emp,cap)))

CPU times: user 19.2 s, sys: 18.2 ms, total: 19.2 s
Wall time: 19.2 s


In [7]:
replace_0_return=np.nan_to_num(return_arr,0)
sort=np.argsort(replace_0_return,axis=0)

In [8]:
# market portfolio is useless, try to use the median return as baseline

In [9]:
replace_0_cap=np.nan_to_num(mar_cap,0)
sort_cap=np.argsort(replace_0_cap,axis=0)

In [10]:
median_arr=[]
for i in range(replace_0_return.shape[1]):
    for j in range(replace_0_return.shape[0]):
        if sort[j][i] == 326:
            median_arr.append(replace_0_return[j][i])

In [11]:
median_arr

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0914464534075104,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 

In [12]:
np.cumsum(np.array(median_arr))

array([  0.        ,   0.        ,   0.        , ..., -19.98130612,
       -19.9254402 , -20.1019733 ])

### Feature generation

In [13]:
from scipy.ndimage.interpolation import shift
sort= -1*(sort-650)
sort_shift_1=shift(sort, [0,1], cval=0)/651
sort_shift_2=shift(sort, [0,2], cval=0)/651
sort_shift_3=shift(sort, [0,2], cval=0)/651
sort_shift_7=shift(sort, [0,7], cval=0)/651

In [14]:
sort_diff = sort_shift_1-sort_shift_2

In [15]:
sort_diff

array([[ 0.        ,  0.9984639 , -0.02918587, ..., -0.3625192 ,
         0.12135177,  0.53763441],
       [ 0.        ,  0.33947773,  0.22734255, ..., -0.1812596 ,
         0.23963134,  0.21505376],
       [ 0.        ,  0.33794163,  0.38402458, ..., -0.59600614,
         0.58832565, -0.09831029],
       ...,
       [ 0.        ,  0.65898618, -0.0030722 , ...,  0.59600614,
         0.21044547, -0.76497696],
       [ 0.        ,  0.68663594, -0.00460829, ...,  0.21351767,
        -0.21351767,  0.16129032],
       [ 0.        ,  0.        ,  0.92012289, ..., -0.02918587,
        -0.3625192 ,  0.0015361 ]])

In [16]:
mar_cap

[array([           nan,            nan,            nan, ...,
        9.06804698e+08, 1.00632851e+09, 1.02126349e+09]),
 array([     nan,      nan,      nan, ..., 1212334., 1196712., 1136195.]),
 array([      nan,       nan,       nan, ..., 17005792., 17383041.,
        17525068.]),
 array([     nan,      nan,      nan, ..., 3947270., 4340761., 4249099.]),
 array([      nan,       nan,       nan, ..., 24224113., 30333043.,
        29939147.]),
 array([   nan,    nan,    nan, ..., 16209., 17724., 17271.]),
 array([     nan,      nan,      nan, ...,  995896., 1264961., 1171148.]),
 array([  nan,   nan,   nan, ..., 7236., 9167., 9717.]),
 array([     nan,      nan,      nan, ..., 2072239., 2022862., 2038364.]),
 array([      nan,       nan,       nan, ..., 15434153., 16240577.,
        16799193.]),
 array([     nan,      nan,      nan, ..., 3626467., 3626467., 3626467.]),
 array([    nan,     nan,     nan, ..., 331283.,  31199., 354785.]),
 array([     nan,      nan,      nan, ...,  760413

### define hyperparameter

In [17]:
cap = 100 #  
t0 = 0 #  train start
t1 = 1200 # test start
t2 = np.shape(return_arr)[1]-1
lag = 1
bottom_num = 10


### select the bottom 10 with high marketcap and tagging

In [18]:
def fetch_data_constraint(bottom_num,cap,lag,start,end):
    #sort_cap_rev= -1*(sort_cap-650)
    arr = []
    for j in range(start-lag,end):
        for i in range(np.shape(return_arr)[0]):
            if (sort_cap[i][j]<=cap) :
                if (sort[i][j]<bottom_num):
                    if not np.isnan(mar_cap[i][j]):
                        arr_ij=[sort_shift_1[i][j],sort_shift_2[i][j],sort_shift_3[i][j],sort_shift_7[i][j],sort_diff[i][j],mar_cap[i][j]]
                        arr_ij.append(1 if return_arr[i][j+lag]>=median_arr[j+lag] else 0)
                        arr.append(arr_ij)
    return arr

In [19]:
train=fetch_data_constraint(bottom_num,cap,lag,t0,t1)

In [20]:
np.unique(np.array(train)[:,6],return_counts=True)

(array([0., 1.]), array([488, 514]))

In [21]:
test=fetch_data_constraint(bottom_num,cap,lag,t1,t2)

In [22]:
np.unique(np.array(test)[:,6],return_counts=True)

(array([0., 1.]), array([220, 214]))

In [23]:
x_train = np.array(train)[:,:5]
y_train = np.array(train)[:,6]
x_test = np.array(test)[:,:5]
y_test = np.array(test)[:,6]

## classifier

### decision tree

In [24]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(clf.predict(x_test),y_test) #?

0.532258064516129

In [26]:
accuracy_score(clf.predict(x_train),y_train)

1.0

In [27]:
#import graphviz 
#dot_data = tree.export_graphviz(clf, out_file=None) 
#graph = graphviz.Source(dot_data) 
#graph.render("1") 

### xgboost

In [28]:
import xgboost as xgb

/usr/local/lib/python3.6/dist-packages/numba/core/errors.py:154: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)


In [29]:
dtrain = xgb.DMatrix(x_train, label=y_train)
dtest = xgb.DMatrix(x_test, label=y_test)
evallist = [(dtest, 'eval'), (dtrain, 'train')]
param = {'max_depth': 5, 'eta': 1, 'objective': 'binary:logistic'}
param['nthread'] = 4
param['eval_metric'] = ['auc','error']

In [30]:
num_round = 100
bst = xgb.train(param, dtrain, num_round, evallist,early_stopping_rounds=50)

[0]	eval-auc:0.50150	eval-error:0.48157	train-auc:0.67985	train-error:0.37824
[1]	eval-auc:0.49122	eval-error:0.52074	train-auc:0.74755	train-error:0.32934
[2]	eval-auc:0.50564	eval-error:0.51843	train-auc:0.79089	train-error:0.29740
[3]	eval-auc:0.51931	eval-error:0.49078	train-auc:0.81459	train-error:0.27744
[4]	eval-auc:0.53360	eval-error:0.47235	train-auc:0.84766	train-error:0.24052
[5]	eval-auc:0.53144	eval-error:0.46313	train-auc:0.86971	train-error:0.21557
[6]	eval-auc:0.54840	eval-error:0.45161	train-auc:0.88990	train-error:0.19860
[7]	eval-auc:0.53628	eval-error:0.47926	train-auc:0.90590	train-error:0.18563
[8]	eval-auc:0.52902	eval-error:0.47696	train-auc:0.92266	train-error:0.16168
[9]	eval-auc:0.53255	eval-error:0.47696	train-auc:0.92796	train-error:0.15669
[10]	eval-auc:0.53483	eval-error:0.48157	train-auc:0.93451	train-error:0.14771
[11]	eval-auc:0.52523	eval-error:0.47926	train-auc:0.94506	train-error:0.14172
[12]	eval-auc:0.52131	eval-error:0.49770	train-auc:0.95343	tra

In [31]:
ypred = bst.predict(dtest, iteration_range=(0, bst.best_iteration))
accuracy_score(np.where(ypred>=0.5,1,0),y_test)

0.5345622119815668

In [32]:
#xgb.plot_tree(bst, num_trees=2)

### light GBM

In [33]:
import lightgbm as lgb

In [34]:
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test)

In [35]:
param = {'num_leaves': 31, 'objective': 'binary'}
param['metric'] = ['auc','error']

In [36]:
num_round = 100
lgb_tree = lgb.train(param, train_data, num_round, valid_sets=[test_data])

[LightGBM] [Info] Number of positive: 514, number of negative: 488
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.031136 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1263
[LightGBM] [Info] Number of data points in the train set: 1002, number of used features: 5
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.512974 -> initscore=0.051908
[LightGBM] [Info] Start training from score 0.051908
[1]	valid_0's auc: 0.493819
[2]	valid_0's auc: 0.486703
[3]	valid_0's auc: 0.491037
[4]	valid_0's auc: 0.488987
[5]	valid_0's auc: 0.480278
[6]	valid_0's auc: 0.489167
[7]	valid_0's auc: 0.493787
[8]	valid_0's auc: 0.498545
[9]	valid_0's auc: 0.498237
[10]	valid_0's auc: 0.491037
[11]	valid_0's auc: 0.491504
[12]	valid_0's auc: 0.494669
[13]	valid_0's auc: 0.5024
[14]	valid_0's auc: 0.505183
[15]	valid_0's auc: 0.502666
[16]	valid_0's auc: 0.503006
[17]	valid_0's auc: 0.506298
[18]	valid_0's auc: 0.508337


## Conclusion:
To real implmentation, median return is not stable. As a result, I will use return=0.003 as baseline to cover the transaction cost.

In [37]:
def fetch_data_constraint_new(bottom_num,cap,lag,start,end):
    #sort_cap_rev= -1*(sort_cap-650)
    arr = []
    arr_return = []
    for j in range(start-lag,end):
        for i in range(np.shape(return_arr)[0]):
            if (sort_cap[i][j]<cap) :
                if (sort[i][j]<bottom_num):
                    if not np.isnan(mar_cap[i][j]):
                        arr_ij=[sort_shift_1[i][j],sort_shift_2[i][j],sort_shift_3[i][j],sort_shift_7[i][j],sort_diff[i][j],mar_cap[i][j]]
                        arr_ij.append(1 if return_arr[i][j+lag]>=0.003 else 0)
                        arr_return.append(return_arr[i][j+lag])
                        arr.append(arr_ij)
    return arr,arr_return

In [38]:
train,return_train=fetch_data_constraint_new(bottom_num,cap,lag,t0,t1)
test,return_test=fetch_data_constraint_new(bottom_num,cap,lag,t1,t2)
np.unique(np.array(train)[:,6],return_counts=True),np.unique(np.array(test)[:,6],return_counts=True)

((array([0., 1.]), array([567, 421])), (array([0., 1.]), array([251, 179])))

In [39]:
x_train = np.array(train)[:,:5]
y_train = np.array(train)[:,6]
x_test = np.array(test)[:,:5]
y_test = np.array(test)[:,6]

In [40]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(clf.predict(x_test),y_test)

0.5232558139534884

In [42]:
dtrain = xgb.DMatrix(x_train, label=y_train)
dtest = xgb.DMatrix(x_test, label=y_test)
evallist = [(dtest, 'eval'), (dtrain, 'train')]
param = {'max_depth': 5, 'eta': 1, 'objective': 'binary:logistic'}
param['nthread'] = 4
param['eval_metric'] = ['auc','error']

In [43]:
num_round = 100
bst = xgb.train(param, dtrain, num_round, evallist,early_stopping_rounds=30)

[0]	eval-auc:0.50882	eval-error:0.41628	train-auc:0.62036	train-error:0.39980
[1]	eval-auc:0.50670	eval-error:0.48372	train-auc:0.69025	train-error:0.34818
[2]	eval-auc:0.47445	eval-error:0.50000	train-auc:0.76228	train-error:0.30769
[3]	eval-auc:0.49268	eval-error:0.48372	train-auc:0.81110	train-error:0.27227
[4]	eval-auc:0.48569	eval-error:0.49767	train-auc:0.82161	train-error:0.26215
[5]	eval-auc:0.49072	eval-error:0.48372	train-auc:0.84781	train-error:0.24393
[6]	eval-auc:0.47002	eval-error:0.48837	train-auc:0.85771	train-error:0.23381
[7]	eval-auc:0.48531	eval-error:0.49302	train-auc:0.88640	train-error:0.19636
[8]	eval-auc:0.49514	eval-error:0.47674	train-auc:0.89743	train-error:0.18522
[9]	eval-auc:0.49278	eval-error:0.48837	train-auc:0.90970	train-error:0.17611
[10]	eval-auc:0.48865	eval-error:0.48140	train-auc:0.91907	train-error:0.17409
[11]	eval-auc:0.48420	eval-error:0.48605	train-auc:0.92165	train-error:0.16802
[12]	eval-auc:0.48726	eval-error:0.47209	train-auc:0.93203	tra

In [44]:
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test)
param = {'num_leaves': 31, 'objective': 'binary'}
param['metric'] = ['auc','error']

In [45]:
num_round = 100
lgb_tree = lgb.train(param, train_data, num_round, valid_sets=[test_data])

[LightGBM] [Info] Number of positive: 421, number of negative: 567
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032926 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1260
[LightGBM] [Info] Number of data points in the train set: 988, number of used features: 5
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.426113 -> initscore=-0.297726
[LightGBM] [Info] Start training from score -0.297726
[1]	valid_0's auc: 0.540998
[2]	valid_0's auc: 0.552483
[3]	valid_0's auc: 0.553418
[4]	valid_0's auc: 0.562832
[5]	valid_0's auc: 0.569532
[6]	valid_0's auc: 0.571446
[7]	valid_0's auc: 0.57326
[8]	valid_0's auc: 0.570355
[9]	valid_0's auc: 0.571724
[10]	valid_0's auc: 0.579258
[11]	valid_0's auc: 0.576921
[12]	valid_0's auc: 0.567039
[13]	valid_0's auc: 0.565192
[14]	valid_0's auc: 0.570723
[15]	valid_0's auc: 0.574785
[16]	valid_0's auc: 0.577322
[17]	valid_0's auc: 0.57651
[18]	valid_0's auc: 0.575987

In [46]:
ypred = lgb_tree.predict(x_test)
ypred

array([0.27611322, 0.67391823, 0.22844742, 0.66032926, 0.50082289,
       0.21356722, 0.39107359, 0.47113472, 0.08172581, 0.71603653,
       0.78361637, 0.22227906, 0.52922977, 0.55672481, 0.61956575,
       0.73085024, 0.85347451, 0.07963434, 0.24796633, 0.34317563,
       0.61215315, 0.81609983, 0.18401609, 0.42647367, 0.65936315,
       0.30052372, 0.60057537, 0.28981584, 0.36097576, 0.62247278,
       0.2810944 , 0.25675702, 0.39213079, 0.15388959, 0.55218389,
       0.25067858, 0.69014867, 0.16090194, 0.1585151 , 0.6755258 ,
       0.29403093, 0.21859324, 0.24364019, 0.67924711, 0.05138291,
       0.59434228, 0.61193127, 0.04578048, 0.40346438, 0.2914847 ,
       0.06764226, 0.81984848, 0.37620523, 0.40894923, 0.23019537,
       0.22014264, 0.80445222, 0.49379998, 0.30763182, 0.51277504,
       0.13816899, 0.4159192 , 0.69664228, 0.52598757, 0.33528085,
       0.62053972, 0.46021814, 0.23044436, 0.1364118 , 0.51839732,
       0.2431147 , 0.1204529 , 0.4400977 , 0.20359512, 0.45407

## simple implementation

### baseline

In [ ]:
np.cumsum(np.array(return_test)-0.002)

In [ ]:
# if we could achieve such high accuracy, we could construct a simple strategy with confidence level,let say simple xgboost

In [ ]:
np.cumsum(np.where(bst.predict(dtest)>0.5,bst.predict(dtest)-0.5,-(0.5-bst.predict(dtest)))*(np.array(return_test)-0.002))

In [ ]:
# we could simply achevie 26% extra return with allowing shorting, however the rough calculation ignores the cash limit(or we say the buy&sell at the same day)

In [ ]:
# simple light GBM

In [ ]:
np.cumsum(np.where(lgb_tree.predict(x_test)>0.5,1-lgb_tree.predict(x_test),-(0.5-bst.predict(dtest)))*(np.array(return_test)-0.002))

In [ ]:
# we could simply achevie -26% return